"""add tournament and league models

Revision ID: 49f1dc35f0d4
Revises: dd647d82b2d4
Create Date: 2026-04-29 08:16:10.650093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f1dc35f0d4'
down_revision: Union[str, None] = 'dd647d82b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowlisted_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowlisted_emails_email'), 'allowlisted_emails', ['email'], unique=True)
    op.create_table('scoring_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'active', 'completed', name='tournamentstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_telegram_admin', sa.Boolean(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('base_points', sa.Integer(), nullable=False),
    sa.Column('base_powerups', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_telegram_username'), 'users', ['telegram_username'], unique=True)
    op.create_table('leagues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_join_code'), 'leagues', ['join_code'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('team1', sa.String(), nullable=False),
    sa.Column('team2', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'live', 'completed', 'cancelled', name='matchstatus'), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('team1_powerplay_score', sa.Integer(), nullable=True),
    sa.Column('team2_powerplay_score', sa.Integer(), nullable=True),
    sa.Column('player_of_the_match', sa.String(), nullable=True),
    sa.Column('more_sixes_team', sa.String(), nullable=True),
    sa.Column('more_fours_team', sa.String(), nullable=True),
    sa.Column('raw_result_json', sa.JSON(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('report_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('match', 'general', name='campaigntype'), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='campaignstatus'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('non_participation_penalty', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=True),
    sa.Column('league_id', sa.String(), nullable=True),
    sa.Column('parent_campaign_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['parent_campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=True),
    sa.Column('league_id', sa.String(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_admin_mappings',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'user_id')
    )
    op.create_table('league_user_mappings',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'user_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('match_winner', sa.String(), nullable=True),
    sa.Column('team1_powerplay', sa.Integer(), nullable=True),
    sa.Column('team2_powerplay', sa.Integer(), nullable=True),
    sa.Column('player_of_the_match', sa.String(), nullable=True),
    sa.Column('more_sixes_team', sa.String(), nullable=True),
    sa.Column('more_fours_team', sa.String(), nullable=True),
    sa.Column('use_powerup', sa.String(), nullable=False),
    sa.Column('is_auto_predicted', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('points_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_match_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('correct_answers', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('toggle', 'multiple_choice', 'dropdown', 'free_text', 'free_number', name='questiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.Column('scoring_rules', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_campaign_mappings',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'campaign_id')
    )
    op.create_table('campaign_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('response_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('answer_value', sa.JSON(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['campaign_questions.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['campaign_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_answers')
    op.drop_table('league_campaign_mappings')
    op.drop_table('campaign_responses')
    op.drop_table('campaign_questions')
    op.drop_table('campaign_match_results')
    op.drop_table('predictions')
    op.drop_table('league_user_mappings')
    op.drop_table('league_admin_mappings')
    op.drop_table('leaderboard_entries')
    op.drop_table('leaderboard_cache')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_leagues_join_code'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_telegram_username'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tournaments')
    op.drop_table('scoring_rules')
    op.drop_index(op.f('ix_allowlisted_emails_email'), table_name='allowlisted_emails')
    op.drop_table('allowlisted_emails')
    # ### end Alembic commands ###
