"""Add MatchStats table

Revision ID: cfd906ace0ce
Revises: dd647d82b2d4
Create Date: 2026-04-26 22:26:47.666147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd906ace0ce'
down_revision: Union[str, None] = 'dd647d82b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('head_to_head', sa.String(), nullable=True),
    sa.Column('favourite', sa.String(), nullable=True),
    sa.Column('form_team1', sa.String(), nullable=True),
    sa.Column('form_team2', sa.String(), nullable=True),
    sa.Column('players_to_watch', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.drop_constraint('uq_campaign_response_user', 'campaign_responses', type_='unique')
    op.create_foreign_key(None, 'matches', 'users', ['reported_by'], ['id'])
    op.alter_column('users', 'is_telegram_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_users_telegram_username'), 'users', ['telegram_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_username'), table_name='users')
    op.alter_column('users', 'is_telegram_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_unique_constraint('uq_campaign_response_user', 'campaign_responses', ['campaign_id', 'user_id'])
    op.drop_table('match_stats')
    # ### end Alembic commands ###
