"""add is_guest to allowlist

Revision ID: dca567bd6876
Revises: e1c329e41572
Create Date: 2026-04-16 18:37:05.994593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca567bd6876'
down_revision: Union[str, None] = 'e1c329e41572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowlisted_emails', sa.Column('is_guest', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allowlisted_emails', 'is_guest')
    # ### end Alembic commands ###
