"""add is_guest

Revision ID: e1c329e41572
Revises: 0a0d524849a5
Create Date: 2026-04-16 18:29:50.582813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1c329e41572'
down_revision: Union[str, None] = '0a0d524849a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions_v2')
    op.drop_table('question_templates')
    op.drop_index('ix_matches_v2_external_id', table_name='matches_v2')
    op.drop_table('matches_v2')
    op.alter_column('predictions', 'is_auto_predicted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'base_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'base_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('users', 'is_guest')
    op.alter_column('predictions', 'is_auto_predicted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('matches_v2',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('venue', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('upcoming', 'live', 'completed', name='matchstatus'), autoincrement=False, nullable=False),
    sa.Column('questions_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('winner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team1_powerplay_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team2_powerplay_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_of_the_match', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_result_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='matches_v2_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_matches_v2_external_id', 'matches_v2', ['external_id'], unique=True)
    op.create_table('question_templates',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('questions_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='question_templates_pkey')
    )
    op.create_table('predictions_v2',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answers_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('match_winner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team1_powerplay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team2_powerplay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_of_the_match', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('use_powerup', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('points_awarded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches_v2.id'], name='predictions_v2_match_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='predictions_v2_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='predictions_v2_pkey')
    )
    # ### end Alembic commands ###
