"""Add match_id to CampaignResponse

Revision ID: efa48ee6e4c9
Revises: 49f1dc35f0d4
Create Date: 2026-04-29 08:46:52.689026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa48ee6e4c9'
down_revision: Union[str, None] = '49f1dc35f0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_campaign_responses_matches', 'matches', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_responses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaign_responses_matches', type_='foreignkey')
        batch_op.drop_column('match_id')
    # ### end Alembic commands ###
